name: kataglyphis_inference_engine
description: "Making an inference with Rust and display the results with Flutter/Dart."
homepage: https://jonasheinle.de

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  jotrockenmitlockenrepo:
    path: ExternalLib/jotrockenmitlockenrepo
  kataglyphis_native_inference:
    path: ExternalLib/Kataglyphis_NativeInferencePlugin
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_rust_bridge: ^2.11.1
  go_router: ^17.1.0
  font_awesome_flutter: ^10.12.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  kataglyphis_rustprojecttemplate:
    path: rust_builder
  permission_handler: ^12.0.1

  provider: any
dev_dependencies:
  mockito: ^5.6.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Pages/AboutMe/
    - assets/images/Pages/AboutMe/Bewerbungsbilder/
    - assets/images/Pages/Data/
    - assets/images/Pages/Error/
    - assets/images/Pages/Blog/
    - assets/images/Pages/Blog/VulkanRenderer/
    - assets/images/cats/
    - assets/images/aiBlog/
    - assets/images/books/
    - assets/documents/
    - assets/documents/footer/
    - assets/documents/blog/
    - assets/data/
    - assets/settings/
    - assets/settings/user_settings/
    - assets/fonts/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
      - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
      - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
      - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
      - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        style: italic
      - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        style: italic
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto/Roboto-Black.ttf
      - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Light.ttf
      - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 400
      - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        weight: 200
      - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
        weight: 200
        style: italic
  - family: Noto Sans
    fonts:
      - asset: assets/fonts/Noto_Sans/static/NotoSans-Regular.ttf
      - asset: assets/fonts/Noto_Sans/static/NotoSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/Noto_Sans/static/NotoSans-Italic.ttf
        style: italic
      - asset: assets/fonts/Noto_Sans/static/NotoSans-BoldItalic.ttf
        style: italic
        weight: 700

flutter_launcher_icons:
  android: true
  image_path: assets/icons/kataglyphis_app_icon.png
  web:
    generate: true
    image_path: assets/icons/kataglyphis_app_icon.png
    background_color: "#0B1220"
    theme_color: "#0B1220"
  windows:
    generate: true
    image_path: assets/icons/kataglyphis_app_icon.png
    icon_size: 256